const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require('jsdom');
test('web demo preserves preview, exclusion, regex, deletion and undo semantics', t => {
  const read = name => fs.readFileSync(path.join(__dirname, '..', name), 'utf8');
  const dom = new JSDOM(read('index.html'), { runScripts: 'outside-only' });
  t.after(() => dom.window.close());
  const w = dom.window, d = w.document, $ = id => d.getElementById(id);
  w.eval(read('rules.js')); w.eval(read('demo.js'));
  const original = $('sourceInput').value;
  const preview = () => $('demoForm').dispatchEvent(new w.Event('submit', { cancelable: true }));
  assert.equal($('output').querySelectorAll('mark').length, 2);
  assert.equal($('applyButton').disabled, true);
  d.querySelector('[data-preset="append"]').click();
  assert.match($('output').textContent, /张小乙（身穿雨衣）/);
  assert.equal($('sourceInput').value, original);
  $('applyButton').click(); $('undoDemoButton').click();
  assert.equal($('sourceInput').value, original);
  d.querySelector('[data-preset="exclude"]').click();
  assert.match($('output').textContent, /远处的神坛/);
  assert.match($('output').textContent, /悬崖祭坛/);
  d.querySelector('[data-preset="regex"]').click();
  assert.match($('output').textContent, /小乙张/);
  $('replacementInput').value = ''; preview();
  assert.equal($('output').textContent.includes('张小乙'), false);
  $('matchInput').value = '['; preview();
  assert.equal($('applyButton').disabled, true);
  $('resetButton').click(); $('wrapButton').click(); $('wrapButton').click();
  assert.equal($('replacementInput').value, '[张小乙]');
  d.querySelector('[data-preset="replace"]').click();
  $('replacementInput').value = '<img src=x onerror=alert(1)>'; preview();
  assert.equal($('output').querySelector('img'), null);
  $('sourceInput').dispatchEvent(new w.Event('input'));
  assert.equal($('applyButton').disabled, true);
});
